# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Only on pushes to master for now
trigger:
- master

# Use jobs so can split into directly hosted (on Azure) and in-Docker
# Not clear yet if/how can use a strategy matrix with VMs and Containers
jobs:
# Job(s) that can run directly in Azure VMs
- job: Azure
  strategy:
    matrix:
      ubuntu-18.04:
        imageName: 'ubuntu-18.04'
      macos-10.14:
        imageName: 'macos-10.14'
      windows-2019:
        imageName: 'windows-2019'
      windows-2017:
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
  - script: brew install boost
    condition: startsWith(variables.imageName,'macos')
  - template: .azure-templates/cmake-steps.yml

# Job that runs in a container on a VM
- job: Docker
  strategy:
    matrix:
      centos-7:
        containerName: 'centos:7'
      centos-8:
        containerName: 'centos:8'
  pool:
    vmImage: 'ubuntu-16.04'
  container: 
    image: $(containerName)
  # Fails for now as we need to install packages in the container,
  # or provide a prebuilt container with those packages
  steps:
  - template: .azure-templates/cmake-steps.yml
