# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# Try per-platform jobs, using template for the steps
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: .azure-templates/cmake-steps.yml
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: .azure-templates/cmake-steps.yml
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: .azure-templates/cmake-steps.yml