# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


strategy:
  matrix:
    ubuntu-18.04:
      imageName: 'ubuntu-18.04'
    macos-10.14:
      imageName: 'macos-10.14'
    windows-2019:
      imageName: 'windows-2019'
    windows-2017:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

jobs:
- job: Azure
  steps:
  - template: .azure-templates/cmake-steps.yml
- job: Azure CentOS7
  pool:
    vmImage: 'ubuntu-16.04'
  container: centos:7